/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Magician
 */
public class JFrameMain extends javax.swing.JFrame {
    public static Persona[] personas = new Persona[2];
    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();
        label_APublica.setText("Persona A publica : "+ personas[0].getPublic());
        label_BPublica.setText("Persona B publica: "+ personas[1].getPublic());
        label_APrivada.setText("Persona A privada: "+ personas[0].getSecret());
        label_BPrivada.setText("Persona B privada: "+ personas[1].getSecret());
        button_C.setEnabled(false);
        button_D.setEnabled(false);
        texField_encripted.setEditable(false);
        textField_desencripted.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_encriptar = new javax.swing.JLabel();
        textField_input = new javax.swing.JTextField();
        label_encriptado = new javax.swing.JLabel();
        texField_encripted = new javax.swing.JTextField();
        label_desencripted = new javax.swing.JLabel();
        textField_desencripted = new javax.swing.JTextField();
        button_A = new javax.swing.JButton();
        button_B = new javax.swing.JButton();
        button_C = new javax.swing.JButton();
        button_D = new javax.swing.JButton();
        label_APublica = new javax.swing.JLabel();
        label_APrivada = new javax.swing.JLabel();
        label_BPublica = new javax.swing.JLabel();
        label_BPrivada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_encriptar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_encriptar.setText("Mensaje a encriptar");

        textField_input.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textField_input.setText("Escribe aqui el input");

        label_encriptado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_encriptado.setText("Mensaje encriptado");

        label_desencripted.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_desencripted.setText("Mensaje desencriptado");

        button_A.setText("Key A publica");
        button_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_AActionPerformed(evt);
            }
        });

        button_B.setText("Key B publica");
        button_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_BActionPerformed(evt);
            }
        });

        button_C.setText("Key A privada");
        button_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CActionPerformed(evt);
            }
        });

        button_D.setText("Key B privada");
        button_D.setToolTipText("");
        button_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_DActionPerformed(evt);
            }
        });

        label_APublica.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_APublica.setText("Key A publica");

        label_APrivada.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_APrivada.setText("Key A privada");

        label_BPublica.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_BPublica.setText("Key B publica");

        label_BPrivada.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_BPrivada.setText("Key B privada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_desencripted, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textField_desencripted, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_encriptado)
                            .addComponent(label_encriptar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button_B)
                                    .addComponent(button_A))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textField_input, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button_D)
                                    .addComponent(button_C))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                                .addComponent(texField_encripted, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_BPrivada)
                    .addComponent(label_BPublica)
                    .addComponent(label_APrivada)
                    .addComponent(label_APublica))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(label_APublica)
                .addGap(4, 4, 4)
                .addComponent(label_APrivada)
                .addGap(18, 18, 18)
                .addComponent(label_BPublica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_BPrivada)
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_A)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_B))
                            .addComponent(label_encriptar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_encriptado)
                                    .addComponent(texField_encripted, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(label_desencripted, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                    .addComponent(textField_desencripted)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_C)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(button_D)))
                        .addGap(105, 105, 105))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textField_input, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_AActionPerformed
        RSA object= new RSA();
        if(personas[0].getPublicKey().getN() >= object.encryptBase26(textField_input.getText())){
    	    object.encryptString(textField_input.getText(), personas[0].getPublicKey());
    	    texField_encripted.setText(""+object.encryptString(textField_input.getText(), personas[0].getPublicKey()));
    	    button_C.setEnabled(true);
    	    button_D.setEnabled(true);
		}
		else{
			texField_encripted.setText("MAXIMUM LENGTH REACHED");
			button_C.setEnabled(false);
			button_D.setEnabled(false);
		}
    }//GEN-LAST:event_button_AActionPerformed

    private void button_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_BActionPerformed
         RSA object= new RSA();
         if(personas[1].getPublicKey().getN() >= object.encryptBase26(textField_input.getText())){
         	object.encryptString(textField_input.getText(), personas[1].getPublicKey());
         	texField_encripted.setText(""+object.encryptString(textField_input.getText(), personas[1].getPublicKey()));
         	button_C.setEnabled(true);
    	 	button_D.setEnabled(true);
	 	 }
	 	 else{
			texField_encripted.setText("MAXIMUM LENGTH REACHED");
			button_C.setEnabled(false);
			button_D.setEnabled(false);
		 }
    }//GEN-LAST:event_button_BActionPerformed

    private void button_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CActionPerformed
        RSA object= new RSA();
        object.decryptString(Long.valueOf(texField_encripted.getText()).longValue(),personas[0].getSecretKey());
        textField_desencripted.setText(""+object.decryptString(Long.valueOf(texField_encripted.getText()).longValue(),personas[0].getSecretKey()));
    }//GEN-LAST:event_button_CActionPerformed

    private void button_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_DActionPerformed
        RSA object= new RSA();
        object.decryptString(Long.valueOf(texField_encripted.getText()).longValue(),personas[1].getSecretKey());
        textField_desencripted.setText(""+object.decryptString(Long.valueOf(texField_encripted.getText()).longValue(),personas[1].getSecretKey()));
    }//GEN-LAST:event_button_DActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


      personas[0]= new Persona();
      personas[1]= new Persona();

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton button_A;
    private static javax.swing.JButton button_B;
    private static javax.swing.JButton button_C;
    private static javax.swing.JButton button_D;
    private static javax.swing.JLabel label_APrivada;
    private static javax.swing.JLabel label_APublica;
    private static javax.swing.JLabel label_BPrivada;
    private static javax.swing.JLabel label_BPublica;
    private javax.swing.JLabel label_desencripted;
    private javax.swing.JLabel label_encriptado;
    private javax.swing.JLabel label_encriptar;
    private static javax.swing.JTextField texField_encripted;
    private static javax.swing.JTextField textField_desencripted;
    private static javax.swing.JTextField textField_input;
    // End of variables declaration//GEN-END:variables
}
